language: go
sudo: false
go:
  - 1.11.x
env:
  global:
    - GO111MODULE=on
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make test
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/gitmv-darwin-amd64
          - cross/gitmv-darwin-amd64.md5
          - cross/gitmv-darwin-amd64.sha256
          - cross/gitmv-linux-amd64
          - cross/gitmv-linux-amd64.md5
          - cross/gitmv-linux-amd64.sha256
        skip_cleanup: true
        on:
          tags: true
notifications:
  slack:
    secure: IEt62nSjuErH/e7Ytb2yJWoODjx8Dw3+G8Udqbe2yFIHbGTiUnSswLrTjZLciyr+WLPiqAYZq2y19mhs+JhzyKwi8GlqeaMfXfAd8yXE2NMKVPcw/vT347zYwDtihRIFHrTdcU7f1o3Xn6ajLhhGc84V+Dl/vU9sfrUXp48vGSv1csr8W4xjo6qtlyd6DMvbHIWfCylPam4Tq4IsTqeJE1w3BqZQLzuSpafMSYwl10+rpSOtKBksY1un8dXVVd/WvVT2CqlEYP7T1LegdHgnN3DthHvn409DospGS9loOkblpFaRzGwkcxALastsD++5gzUne2skTOwkR4Ra0v+qmooz+vrFGY4SGmXkfXUXVpw+FRDI/nOjOm/QrSHST2G1joey0HmjzlFllh04GjQ0m0n6p5uJ4iYwYRGxOoEYcRjwDDBdMFQel0+nc6M5AmHqce85eD+7SW5QjIxAeETmEz8AKA9vPK/xyAmnE/qjz4nngSf9xF7M3GyHpY/zo/gbCi40AXSNuNpzpBzscUsENaLj1yWOgT8jEu+/AGqKs8+B/Q5XPyRd6nTx8333lEYFXWiNaeYrui/boQf9IRzx0gagmK0HxAOCh2yTSvmw6OVBlwqS7u/KBGjR+eb6qFHzaZBxvpbR61SaNSaIaJWzM4dOBbwMzy8FtVoofHEyMO4=
